### PR TITLE
Feat #74 : Create a Story Component

### LINKED ISSUE #74: [Feature] Implementing Story UI on Home page
### Description

as i see the FIGMA Design file of the Website their is a story section on the home Page That improve the Page ui And application 

I want to work on this ui feature please assign me that

### Screenshots

Screenshot_2024-05-15-11-08-49-37_40deb401b9ffe8e1df2f1cc5ba480b12

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by CoderSwarup**
## Fixes Issue
close #74

## Changes proposed

create a Story Ui component similar to the instagram story feed section where user others user story. Here's a sample video demonstrating the UI: [video](https://fileport.io/EuNFatv6CJse).

## Screenshots

storyui

storyui2

## Note to reviewers

Here's the frontend work I've completed. If you'd like to implement the backend (using Appwrite) to fetch real user data for the stories and display it, please let me know.

### CODE REVIEW

**Review by Nishitbaria — CHANGES_REQUESTED** [review]
Hey @CoderSwarup  We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss 

Second Point 

image


Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic


image


User must be able to upload Story

**Comment by Nishitbaria** [comment]
> > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > Second Point
> > image
> > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > image
> > User must be able to upload Story
> 
> ok
> 
> one query that i use my own appwrite or you can provide the your appwrite access to me

for now I will provide you my dummy appwrite account : 

use this as id and pass : limamex886@godsigma.com

**Comment by CoderSwarup** [comment]
> > > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > > Second Point
> > > image
> > > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > > image
> > > User must be able to upload Story
> > 
> > 
> > ok
> > one query that i use my own appwrite or you can provide the your appwrite access to me
> 
> for now I will provide you my dummy appwrite account :
> 
> use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)

image

please check the ui

**Comment by Nishitbaria** [comment]
> > > > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > > > Second Point
> > > > image
> > > > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > > > image
> > > > User must be able to upload Story
> > > 
> > > 
> > > ok
> > > one query that i use my own appwrite or you can provide the your appwrite access to me
> > 
> > 
> > for now I will provide you my dummy appwrite account :
> > use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)
> 
> image
> 
> please check the ui

Just change button color other vice other things LGTM

**Comment by CoderSwarup** [comment]
> > > > > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > > > > Second Point
> > > > > image
> > > > > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > > > > image
> > > > > User must be able to upload Story
> > > > 
> > > > 
> > > > ok
> > > > one query that i use my own appwrite or you can provide the your appwrite access to me
> > > 
> > > 
> > > for now I will provide you my dummy appwrite account :
> > > use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)
> > 
> > 
> > image
> > please check the ui
> 
> Just change button color other vice other things LGTM

image

check now 

image

and any changes required here

**Comment by Nishitbaria** [comment]
> > > > > > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > > > > > Second Point
> > > > > > image
> > > > > > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > > > > > image
> > > > > > User must be able to upload Story
> > > > > 
> > > > > 
> > > > > ok
> > > > > one query that i use my own appwrite or you can provide the your appwrite access to me
> > > > 
> > > > 
> > > > for now I will provide you my dummy appwrite account :
> > > > use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)
> > > 
> > > 
> > > image
> > > please check the ui
> > 
> > 
> > Just change button color other vice other things LGTM
> 
> image
> 
> check now
> 
> image
> 
> and any changes required here in the story view Model

**Don't make it Transparent make the background blurry**

**Comment by Nishitbaria** [comment]
> > use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)
> 
> ok 
> please give me the password of the appwrite 

This email is both email and password

**Comment by Atharva1723** [comment]
> > > > > > > Hey @CoderSwarup We are only using Shadcn and tailwind CSS please don't use Normal Css please convert this Tailwindcss
> > > > > > > Second Point
> > > > > > > image
> > > > > > > Check the Figma file its not look same as file contain please follow same typography as Figma file contain and this story not be a static its should be Dynamic
> > > > > > > image
> > > > > > > User must be able to upload Story
> > > > > > 
> > > > > > 
> > > > > > ok
> > > > > > one query that i use my own appwrite or you can provide the your appwrite access to me
> > > > > 
> > > > > 
> > > > > for now I will provide you my dummy appwrite account :
> > > > > use this as id and pass : [limamex886@godsigma.com](mailto:limamex886@godsigma.com)
> > > > 
> > > > 
> > > > image
> > > > please check the ui
> > > 
> > > 
> > > Just change button color other vice other things LGTM
> > 
> > 
> > image
> > check now
> > image
> > and any changes required here in the story view Model
> 
> **Don't make it Transparent make the background blurry**

Similar when we press logout the background , its currently transparent it should be blurry !

**Comment by CoderSwarup** [comment]
@Nishitbaria i got the following error when i try to make any operation in appwrite 

`AppwriteException: The current user is not authorized to perform the requested action. i got this error `

please tell me what is an issue

**Comment by CoderSwarup** [comment]
@Nishitbaria please check the changes

**Comment by Nishitbaria** [comment]
> @Nishitbaria please check the changes

please fix the conflicts

**Comment by CoderSwarup** [comment]
@Nishitbaria  conflicts Resolve sample video link [here](https://fileport.io/M68DebKF2xcE)

Before trying the please change the VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664701060006ef1071bf"  add this env with main appwrite with attribute 


image

**Comment by Nishitbaria** [comment]
> @Nishitbaria conflicts Resolve sample video link [here](https://fileport.io/M68DebKF2xcE)
> 
> Before trying the please change the VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664701060006ef1071bf" add this env with main appwrite with attribute
> 
> image

Can you please provide me appwrite.json

**Comment by CoderSwarup** [comment]
> > @Nishitbaria conflicts Resolve sample video link [here](https://fileport.io/M68DebKF2xcE)
> > Before trying the please change the VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664701060006ef1071bf" add this env with main appwrite with attribute
> > image
> 
> Can you please provide me appwrite.json

I use your give credentials for login limamex886@godsigma.com you can directly access this

**Comment by CoderSwarup** [comment]
@Nishitbaria any update

**Comment by Nishitbaria** [comment]
> @Nishitbaria any update 

I check one thing is that it's not align with. Current db I have config for that

**Comment by CoderSwarup** [comment]
> > @Nishitbaria any update
> 
> I check one thing is that it's not align with. Current db I have config for that

ok 
which config file you need 

if you need appwrite.json file 
so please help me  to  generate the  appwrite config file how i can do that 

already available config file is 
[appwrite.json](https://github.com/Nishitbaria/OpenGrame/files/15369698/appwrite.json)

**Comment by Nishitbaria** [comment]
> > > @Nishitbaria any update
> > 
> > 
> > I check one thing is that it's not align with. Current db I have config for that
> 
> ok which config file you need
> 
> if you need appwrite.json file so please help me to generate the appwrite config file how i can do that
> 
> already available config file is [appwrite.json](https://github.com/Nishitbaria/OpenGrame/files/15369698/appwrite.json)

Just wait for more 1 day I will try to solve that all issue tomorrow is my last paper

**Comment by Nishitbaria** [comment]
Hey @CoderSwarup  I have added new project on appwrite add your stories Schema on User Schema Look at on appwrite

**Comment by CoderSwarup** [comment]
> Hey @CoderSwarup I have added new project on appwrite add your stories Schema on User Schema Look at on appwrite

Ok

**Comment by Nishitbaria** [comment]
> > Hey @CoderSwarup I have added new project on appwrite add your stories Schema on User Schema Look at on appwrite
> 
> Check the project i added story schema

when User Create Post then there is ref of the post in Both Post and User Schema There is between relationship i didn't find that you make any kind of relationship its require to store the reference that who added the stories : 

image

**Comment by CoderSwarup** [comment]
> > > Hey @CoderSwarup I have added new project on appwrite add your stories Schema on User Schema Look at on appwrite
> > 
> > 
> > Check the project i added story schema
> 
> when User Create Post then there is ref of the post in Both Post and User Schema There is between relationship i didn't find that you make any kind of relationship its require to store the reference that who added the stories :
> 
> image

No need to define relationship between them the stories are fetch based on the accountid that is handling on the api 

Directly add the story schema in appwrite db

**Comment by CoderSwarup** [comment]
@Nishitbaria any problem is their

**Comment by Nishitbaria** [comment]
> @Nishitbaria any problem is their

image

**Comment by CoderSwarup** [comment]
> > @Nishitbaria any problem is their
> 
> image

please check now

**Comment by Nishitbaria** [comment]
Hey @CoderSwarup  Stories is upload and second think i want to say that did you implemented that logic that after 24hour storis is automatically removed ?

**Comment by Nishitbaria** [comment]
@CoderSwarup  Everythings Looks Good But I found Two bugs 

1. When as User i first time added Stories its visible to everyone 
2. but when i try to upload Stories then its uploaded but not visible for other as well for me

**Comment by CoderSwarup** [comment]
> @CoderSwarup Everythings Looks Good But I found Two bugs
> 
> 1. When as User i first time added Stories its visible to everyone
> 2. but when i try to upload Stories then its uploaded but not visible for other as well for me

bug : When you upload the second story in story feed section you and other user see the old story means 1st , it's write or the 2nd story complete not visible?

**Comment by Nishitbaria** [comment]
> > @CoderSwarup Everythings Looks Good But I found Two bugs
> > 
> > 1. When as User i first time added Stories its visible to everyone
> > 2. but when i try to upload Stories then its uploaded but not visible for other as well for me
> 
> bug : When you upload the second story in story feed section you and other user see the old story means 1st , it's write or the 2nd story complete not visible?

Yea When i login with second account then its show first account stories but when i upload with second account stories then its uploaded but not visible on my profile as well for other profile too @CoderSwarup

**Comment by CoderSwarup** [comment]
> second account then its show first account stories but when i upload with second account stories then its uploaded but not v

you need to reload the page of the user

**Comment by CoderSwarup** [comment]
@Nishitbaria 

User 1 Story Visible on user 2 Account
image

User 1 Upload Story 

image

User 1 Story Uploaded Successfully 
image


On user 2 Story Shows the old Data  before reload 
image


After reload On user 2
image

**Comment by Nishitbaria** [comment]
@CoderSwarup  See
Uploading OpenGrame and 1 more page - Personal - Microsoft​ Edge 2024-05-26 11-58-13.mp4…

**Comment by CoderSwarup** [comment]
> @CoderSwarup See Uploading OpenGrame and 1 more page - Personal - Microsoft​ Edge 2024-05-26 11-58-13.mp4…


video is not upload

**Comment by Nishitbaria** [comment]
> > @CoderSwarup See Uploading OpenGrame and 1 more page - Personal - Microsoft​ Edge 2024-05-26 11-58-13.mp4…
> 
> video is not upload

https://github.com/Nishitbaria/OpenGrame/assets/85815172/25fa6365-a2d6-451e-ba21-f09ac923d978

**Comment by CoderSwarup** [comment]
ok bug is when you upload your story then it will be not showing itself

**Comment by Nishitbaria** [comment]
> ok bug is when you upload your story then it will be not showing itself

Yes and also for other too

**Comment by CoderSwarup** [comment]
Ok i will see that, can you send me your envs

**Comment by Nishitbaria** [comment]
> Ok i will see that, can you send me your envs

```
VITE_APPWRITE_PROJECT_ID="664b72c700235fef3e76"
VITE_APPWRITE_URL="https://cloud.appwrite.io/v1"
VITE_APPWRITE_STORAGE_ID="65478ceca6d8a49b3cf1"
VITE_APPWRITE_DATABASE_ID="3j22cy28uc3"
VITE_APPWRITE_SAVES_COLLECTION_ID="65479a44782ab930d6f3"
VITE_APPWRITE_USERS_COLLECTION_ID="65479b3f3ff36d0c3fa6"
VITE_APPWRITE_POSTS_COLLECTION_ID="65479a1224b7d12ccb6e"
VITE_APPWRITE_STORIES_COLLECTION_ID="664c1dba0005c3bb2eae"
```

**Comment by CoderSwarup** [comment]
@Nishitbaria 

Their is an error in you env 

```
VITE_APPWRITE_PROJECT_ID="664b72c700235fef3e76"
VITE_APPWRITE_URL="https://cloud.appwrite.io/v1"
VITE_APPWRITE_STORAGE_ID="65478ceca6d8a49b3cf1"
VITE_APPWRITE_DATABASE_ID="3j22cy28uc3"
VITE_APPWRITE_SAVES_COLLECTION_ID="65479a44782ab930d6f3"
VITE_APPWRITE_USERS_COLLECTION_ID="65479b3f3ff36d0c3fa6"
VITE_APPWRITE_POSTS_COLLECTION_ID="65479a1224b7d12ccb6e"
VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664c1dba0005c3bb2eae"  
``` 

when i try its Work Perfectly also i see your Stories also 

[video](https://fileport.io/JkwPecJGaRkq)

**Comment by Nishitbaria** [comment]
> @Nishitbaria 
> 
> Their is an error in you env 
> 
> ```
> VITE_APPWRITE_PROJECT_ID="664b72c700235fef3e76"
> VITE_APPWRITE_URL="https://cloud.appwrite.io/v1"
> VITE_APPWRITE_STORAGE_ID="65478ceca6d8a49b3cf1"
> VITE_APPWRITE_DATABASE_ID="3j22cy28uc3"
> VITE_APPWRITE_SAVES_COLLECTION_ID="65479a44782ab930d6f3"
> VITE_APPWRITE_USERS_COLLECTION_ID="65479b3f3ff36d0c3fa6"
> VITE_APPWRITE_POSTS_COLLECTION_ID="65479a1224b7d12ccb6e"
> VITE_APPWRITE_STORIES_DATA_COLLECTION_ID="664c1dba0005c3bb2eae"  
> ``` 
> 
> when i try its Work Perfectly also i see your Stories also 
> 
> see the video
> 
> [video](https://fileport.io/JkwPecJGaRkq)
> 
> and also its work When i upload the New Story without reloading 
> 
> image
> 
> its Take Time To Load the new Story Image

I have just last question that did you implement Automatic Remove stories feature ?

**Pull request merged**
