### PR TITLE
[Feature] : Logout Alerting Screen

### PR DESCRIPTION
**Pull request by sivaprasath2004**
#36 
## Fixes Issue
- The logout Alerting screen was successfully added
-close the issue #36 

## Changes proposed
- `useState` will be added 
- `Inline css` writting

## Screenshots
[Screencast from 2024-05-12 10-15-13.webm](https://github.com/Nishitbaria/OpenGrame/assets/121082414/ea4fd672-b756-44f5-8e82-0809db5d693b)

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@Nishitbaria I will finishing New feature please merged it.

**Comment by Nishitbaria** [comment]
> @Nishitbaria I will finish new feature please merge it.

Hey, can you change the Styling of the button? 

Figma file : [here](https://www.figma.com/file/y7OzDDuGVslwr9rOYDQ7i2/OpenGrame?type=design&node-id=0%3A1&mode=design&t=aMzewIEoN9dd3iFD-1)

also, Take Ref Modal: Because we are using shadcn then please use this component for Dialog : [click](https://ui.shadcn.com/docs/components/dialog)

**Comment by sivaprasath2004** [comment]
Sure

**Comment by sivaprasath2004** [comment]
@Nishitbaria code will be change and add `hover` effect.
[Screencast from 2024-05-12 12-19-53.webm](https://github.com/Nishitbaria/OpenGrame/assets/121082414/0b28c6c7-c671-45b9-9401-f74d308c65dd)

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-05-12 12-19-53.webm](https://github.com/Nishitbaria/OpenGrame/assets/121082414/f88bcada-9de7-4a6e-a5de-733d6f975537)

**Review by Nishitbaria — CHANGES_REQUESTED** [review]
Hey @sivaprasath2004 I tell like to use the Dialog component from the Shadcn Modal to become reusable 

here is the Link checkout this and integrate into the modal : https://ui.shadcn.com/docs/components/alert-dialog

**Comment by sivaprasath2004** [comment]
@Nishitbaria Thank you for recomanding i'm just learning in react it is more useful for me thank you. If this `correcct` please message .

[Screencast from 2024-05-12 14-58-03.webm](https://github.com/Nishitbaria/OpenGrame/assets/121082414/ee40ec0f-62c1-4ea5-8b92-3fabba2b7b37)

**Comment by Nishitbaria** [comment]
Please fix the conflict 🙏

**Comment by sivaprasath2004** [comment]
@Nishitbaria fix it.sorry for the some mistakes...

**Comment by Nishitbaria** [comment]
> @Nishitbaria fix it.sorry for the some mistakes...

image

**Comment by Nishitbaria** [comment]
Do you know about TypeScript? @sivaprasath2004

**Comment by sivaprasath2004** [comment]
I don't know place add the package @Nishitbaria

**Comment by avayyyyyyy** [comment]
Hey! @Nishitbaria I can work on this issue.

**Pull request closed without merging**
