### PR TITLE
fixes: height overflow in register and login page

### LINKED ISSUE #10: [BUG] Fixing register page UI
### Description

Currently, register page UI overflows at the bottom. I can fix it by making left side scrollbar only and right side fixed. 

### Screenshots

Screenshot (219)

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by raghavawasthi24**
Closes #10

## Changes proposed

1. Fixed height of register page
2. Made left side scrollable
3. Hide scrollbar 

## Screenshots

Screenshot (222)

### CODE REVIEW

**Review by Nishitbaria — CHANGES_REQUESTED** [review]
Change is looking LGTM but one issue I found that 

image

See the open Grame Logo its Cut at the top Can you  add some margin to remove that cut  ?

**Comment by raghavawasthi24** [comment]
@Nishitbaria I had fixed the logo

**Comment by Nishitbaria** [comment]
Great Work @raghavawasthi24

**Review by Nishitbaria — APPROVED** [review]
Great Work @raghavawasthi24 I approve this changes

**Comment by raghavawasthi24** [comment]
@Nishitbaria can you please give level 2 tag?

**Pull request merged**
