### PR TITLE
[Feature] - Custom 404 Not Found page added

### PR DESCRIPTION
**Pull request by sambitsingha**
## Changes proposed
``tailwind.coffig.js`` - Added the background image of 404 page
``Custom404.jsx`` - the file containing the 404 page

## Screenshots

Screenshot (353)

## Note to reviewers

I have tested this on multiple places -- do perform ur check, if there is a problem, I am open to soleving it.

### CODE REVIEW

**Comment by sambitsingha** [comment]
@Nishitbaria Kidnly review the PR

**Review by Nishitbaria — APPROVED** [review]
Looking Good To me ✨

**Comment by Nishitbaria** [comment]
Thank you for your contribution @sambitsingha

**Comment by sambitsingha** [comment]
## @Nishitbaria Please add the gssoc and level label as it is important

**Comment by sambitsingha** [comment]
@Nishitbaria Please label it

**Pull request merged**
