### PR TITLE
Authenciation and security features added

### PR DESCRIPTION
**Pull request by khy05dua**
I have made changes regarding authenciation and logging in website if user enabled multifactor authrntication they will get their recovery codes and on typing paswword wrong 3 times in singup page it will ask for recovery codes and upon writing the correct one then only it will aloow user to enter ,it also has a feature of verifying email.
Thnakyou

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> I have made changes regarding authenciation and logging in website if user enabled multifactor authrntication they will get their recovery codes and on typing paswword wrong 3 times in singup page it will ask for recovery codes and upon writing the correct one then only it will aloow user to enter ,it also has a feature of verifying email. Thnakyou

you can mention the issue number on which issue are you working ?

**Comment by khy05dua** [comment]
> > I have made changes regarding authentication and logging in website if user enabled multifactor authentication they will get their recovery codes and on typing password wrong 3 times in signup page it will ask for recovery codes and upon writing the correct one then only it will allow user to enter ,it also has a feature of verifying email. Thankyou
> 
> Can you mention the issue number on which issue are you working ?
> issue no. #115

**Comment by khy05dua** [comment]
Issue No.115

**Comment by Nishitbaria** [comment]
Hey @khy05dua Can you explain what you changed I mean you changed in more than 42 files and nothing sees any things related new in the auth

**Pull request closed without merging**
