### PR TITLE
Added Legal Pages

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #108 

@Nishitbaria I added the Legal Pages and I have linked the pages in the settings

image

image

image

image

Please check and let me know if any changes are required.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @Hemashree21  There is One Issue where I and contributor has change major things once its merger then i will merge this pr 
Till that wait for that I hope you understand

**Comment by Hemashree21** [comment]
@Nishitbaria yeah sure no problem!

**Comment by Nishitbaria** [comment]
Hey @Hemashree21  Please Resolve Conflicts

**Comment by Hemashree21** [comment]
@Nishitbaria I resolved the conflicts

image

I updated settings page also

**Comment by Hemashree21** [comment]
Can you please add the gssoc and level labels?

**Comment by Hemashree21** [comment]
@Nishitbaria can you please check this pr?

**Comment by Nishitbaria** [comment]
> @Nishitbaria can you please check this pr?

Wait for some time I will review it in short time

**Comment by Hemashree21** [comment]
> > @Nishitbaria can you please check this pr?
> 
> Wait for some time I will review it in short time

Okay sure!

**Comment by Nishitbaria** [comment]
Hey @Hemashree21  Please fix this deployment issue: 

image

**Comment by Hemashree21** [comment]
@Nishitbaria I fixed it

**Review by Nishitbaria — APPROVED** [review]
Thank you for your contribution @Hemashree21

**Comment by Hemashree21** [comment]
@Nishitbaria thankyou!

**Pull request merged**
