### PR TITLE
Added Invite Functionality

### PR DESCRIPTION
**Pull request by prafulnigam**
## Changes proposed

Added a Invite Functionality over left-navbar

## Screenshots

Screenshot 2024-05-12 121516

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> ### Closes #22


Hey @prafulnigam  Issue remain same 

WhatsApp Image 2024-05-12 at 13 28 16_2952df86

**Comment by prafulnigam** [comment]
Hey man ! Can you brief me on what are you expecting with the UI Arrangement.

**Comment by Nishitbaria** [comment]
> Hey man ! Can you brief me on what are you expecting with the UI Arrangement.

Ensure that the last two buttons remain within the scope of the left sidebar, as they currently extend beyond it. Please refer to the Figma file for the correct alignment consistent with the design specifications. [Link](https://www.figma.com/file/y7OzDDuGVslwr9rOYDQ7i2/OpenGrame?type=design&node-id=0%3A1&mode=design&t=tiwg9d8hn1NWFjGq-1)

**Comment by prafulnigam** [comment]
Okay gotcha ! They were like that originally, that's why I didn't work over that. I'll fix it up

**Comment by Nishitbaria** [comment]
> Okay gotcha ! They were like that originally, that's why I didn't work over that. I'll fix it up

Any updates @prafulnigam

**Pull request closed without merging**
