### PR TITLE
Hover animation on cards

### LINKED ISSUE #11: [Feature] Hover animation on card
### Description

There is no hover animation on cards, an hover effect  must be there.

### Screenshots

Screenshot (220)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/OpenGrame/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by raghavawasthi24**
Closes #11 

## Changes proposed

Added hover animation on cards in explore section

## Screenshots

https://github.com/Nishitbaria/OpenGrame/assets/113261155/c6255e87-c1d0-4432-bc02-67052aa82259

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @raghavawasthi24 please take reference from here: https://tailwindcomponents.com/component/card-with-hover-animation

I want this type of card hover Effect

**Comment by raghavawasthi24** [comment]
@Nishitbaria I have changed hover effect as refrenced.

**Comment by Nishitbaria** [comment]
> @Nishitbaria I have changed the hover effect as referenced.

Good work  @raghavawasthi24  ✨

**Review by Nishitbaria — APPROVED** [review]

**Comment by raghavawasthi24** [comment]
@Nishitbaria I think you forget to label this PR with gssoc?

**Pull request merged**
